### ISSUE TITLE
config: remove default config and assume the project root has either a .git or go.mod

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#101]
Remove the default config and instead error if there is no `.gunkconfig` found. Currently we assume the project root to be the directory containing a `go.mod` file, we should also check for a `.git/` directory, and if we find one assume that is the project root.

**Comment by mvdan** [comment]
Note - the existence of `.git`, even as a file, should still stop the walker. I believe checked out submodules have a file/symlink for their git dir, since it hangs from the main git dir.
