### ISSUE TITLE
error if gunk tags are found in unexpected comments

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#103]
Currently gunk tags are expected to be on the package declaration and interface function declarations. It would be quite easy to add gunk tags elsewhere and assume they would work. We should attempt to catch these and error if the gunk tag is somewhere unexpected if possible.

**Comment by mvdan** [comment]
Note to self - a good way to do this would likely be to wrap parsing and printing in `gunk/loader`, having it remove gunk tags from `ast.File` and store them elsewhere. Then, it would be this wrapped parser that would error if it finds any Gunk tag in an unusual location.

**Comment by karelbilek** [comment]
Fixed in https://github.com/gunk/gunk/commit/08f9d220d395bc9ee8113dfc01c640157db0bb1a
