### ISSUE TITLE
gunk tags for proto file options

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#104]
Add `FileOption` (https://github.com/golang/protobuf/blob/master/protoc-gen-go/descriptor/descriptor.proto#L318) to be configurable to be used in the `FileDescriptorProto` (https://github.com/golang/protobuf/blob/master/protoc-gen-go/descriptor/descriptor.proto#L79).

Currently we are only setting to `go_package` file options. There should be a way to configure these options. We can check the package declaration for any gunk tags for gunk options (https://github.com/gunk/opt/blob/master/opt.gunk).

```
// Package foo is awesome. This doc paragraph is optional.
//
// +gunk opt.JavaPackage("com.some.package")
// +gunk opt.EtcEtc(whatever)
package foo
```

**Comment by kenshaw** [comment]
I believe I had this in the original example as well.

Not sure if the `http.*` options are being mapped properly to the various Google options, but we should have a generic mapping for these, and we should probably reorganize the heirarchy. For example, the `java_package` and `php_package` options should probably be: `php.Package` and `java.Package`. In that way, the actual options in the Gunk declaration look like:

```
// my package
package mypackage

import (
   "github.com/gunk/opt/java"
)

// +gunk java.Package("com.some.package")
```

**Comment by mvdan** [comment]
Is there a reason why these package-level options should go anywhere, and not just the comment attached to the package clause? Seems to me like it would be best to encourage keeping them all near the top of Gunk files.

**Comment by vishen** [comment]
We would have for java as an example (for the gunk opt package):
```
// github.com/gunk/opt/java/java.gunk
package java

type Package string
type OuterClassname string
type MultipleFiles bool
StringCheckUtf8 bool
```

and have one for each language?

**Comment by vishen** [comment]
(the above are taken from https://github.com/golang/protobuf/blob/master/protoc-gen-go/descriptor/descriptor.proto#L318)

**Comment by vishen** [comment]
I have created a PR for `opt` with the described hierarchy - https://github.com/gunk/opt/pull/3.

**Comment by vishen** [comment]
Ah, I forgot to link this issue in the PR or commit, but some of this has been implemented in https://github.com/gunk/gunk/pull/111. 

The changes will only look for `FileOptions` in the Go package declaration comment, not sure if we want to leave it this way or also look at "hanging" comments for `FileOptions`.

`MethodOptions`, `ServiceOptions`, `FieldOptions`, `MessageOptions`, `EnumOptions` and `EnumValueOptions` are only applied to their respective proto type. A `MethodOption` field will error if specified on a `message` or any type that isn't a method on a `service`.

**Comment by vishen** [comment]
This has been in master for over a month now, so I will close this issue.
