### ISSUE TITLE
Running Gunk without Go installed

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#125]
I was trying to use Gunk in a Docker container without Go installed and ran into the following error:

```
/examples/util # gunk generate -v -x .
error: couldn't exec 'go [list -e -json -compiled -test=false -export=false -deps=false -find=true -- .]': exec: "go": executable file not found in $PATH *exec.Error
```

If we need to have a hard dependency on Go, I think we may need to add something to the documentation about requiring Go installed?

**Comment by mvdan** [comment]
True. To completely remove the dependency on the `go` tool we'd need to remove the use of `go/packages`, which would complicate things quite a lot. We'd drop module support, we'd have to write our own replacement code or use deprecated libraries like https://github.com/kisielk/gotool, and so on.

So my vote goes for just documenting this properly. Gunk is very heavily based on Go, and sort of built on top of its development environment, so I think it's fine to require it. Worst case scenario, we can always have the `gunk` tool download Go somewhere if needed, just like we plan on doing for `protoc` and other run-time dependencies.

**Comment by jwangsadinata** [comment]
Nice find @vishen, I think I agree with you guys with adding the documentation for this. I can work on adding the part on adding `go` as a requirement in the documentation.

**Comment by mvdan** [comment]
@jwangsadinata please don't fix this issue with that PR, as I also think that gunk should error gracefully if any of the tools needed aren't installed. The error shown above just shows too much internal detail and is plain confusing.

**Comment by mvdan** [comment]
Actually, I think it's just `go/packages` that's exposing too much internal detail. I've raised https://github.com/golang/go/issues/29552; we'll see how that turns out.

**Comment by mvdan** [comment]
The upstream error now says `requires 'go' to be installed`, so I'm closing this as fixed.
