### ISSUE TITLE
generate: -o option similar to protoc to dump a FileDescriptorSet

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#136]
When trying to debug differences between what Gunk generates, and what protoc generates for the `FileDescriptorSet`, it might be useful to be able to dump, from Gunk, the `FileDescriptorSet` to a file which we can then compare with protoc's generated `FileDescriptorSet`.

Protoc has these options for dumping the generated `FileDescriptorSet`:

```
  -oFILE,                     Writes a FileDescriptorSet (a protocol buffer,
    --descriptor_set_out=FILE defined in descriptor.proto) containing all of
                              the input files to FILE.
  --include_imports           When using --descriptor_set_out, also include
                              all dependencies of the input files in the
                              set, so that the set is self-contained.
```

**Comment by mvdan** [comment]
My only worry is that `go build -o` means writing a binary file, not an internal descriptor file. So a `gunk convert -o` or `gunk build -o` might confuse users.

Perhaps we could have a `gunk dump [args]` which dumps a gunk file or package as a proto file. For example, it could output JSON by default, and have a `-raw` flag to output the non-plaintext proto directly.

**Comment by vishen** [comment]
`gunk dump` does seem a much better option than following protoc's -o approach.
