### ISSUE TITLE
What are the use-cases for this project

### ISSUE THREAD

**Issue by dan-compton** [gunk/gunk#170]
After skimming, I'm not exactly sure what the underlying intention is here (forgive me not trying to be rude).   Is the intention to simplify protoc-plugin invocation?   

How will this integrate with bazel?

**Comment by kenshaw** [comment]
Hi Dan,

The tool is internally used at Brankas (https://brank.as/), and we don't use Bazel. I understand there are many organizations that have adopted Bazel, and we'd be willing to support it on this project -- that said, it's not high on our priority list, but we'd entertain a well written PR! I have limited exposure to Bazel, but I'm sure it would be straightforward to build some kind of intermediate exec step that could use Gunk.

The intention is to create a better, simplified, standardized workflow for using Protocol Buffers. At Brankas, we don't build anything not written in Go, and this closes the loop for us (ie, developers new to our team / APIs only need to learn "Go", and not Go + proto3). We believe that `gunk` can be leveraged by non-Go shops/projects (it works just fine, for example, for generating Python, Java, JavaScript, et al), but the target audience is primarily those already with extensive protobuf toolchains / build systems.

Thanks for taking a look at the project -- any feedback / comments / thoughts / opinion on the direction this project takes (or any well written PR!) would be greatly appreciated!

**Comment by dan-compton** [comment]
I'm extremely familiar with this issue as I bootstrapped our Ads team on GRPC+Protobuf+protoc and have written a number of protoc plugins including grpc-gateway-cors along and many others.   Fight the good fight, my friend.

For better or worse, I now live in bazel land and bazel owns every aspect of the build -- especially protobuf generation (see rules_go) and dependencies.

The one contribution that I could probably make is just to point you to a repo with a protoc plugin that could transform the [way you work with GRPC services](https://github.com/dan-compton/protoc-gen-grpc-funcs) (concept is solid but needs a bit of work on plugin side).   If you need cors support (I saw grpc-gateway mentioned)  I recommend cleaning up and using https://github.com/dan-compton/grpc-gateway-cors


Aside from that, I'd have to take a deeper look to get intuition on what you really want to accomplish with this.

**Comment by kenshaw** [comment]
@dan-compton thanks for the pointer. Since that's a standard `protoc-gen-*` generator, it would be usable with Gunk definitions. Here's a quick example of adding it to an existing gunk project:

```sh
$ go get -u github.com/dan-compton/protoc-gen-grpc-funcs
$ cd ~/src/ && git clone https://github.com/gunk/gunk-example-server.git && cd gunk-example-server
$ cat .gunkconfig
; generate go libs, with grpc plugins
[generate go]
	plugins=grpc

; generate js libs
[generate js]

; generate python libs
[generate python]

; generate swagger configs, writing files to .
[generate swagger]
	out=.
$ echo -e "\n[generate grpc-funcs]\n" >> .gunkconfig
$ gunk generate ./...
```

That will place `all.funcs.go` (the output of the `protoc-gen-grpc-funcs` generator) in the `v1/util` dir:

```sh
$ $ ls v1/util/
all.funcs.go  all_pb2.py  all.pb.go  checkstatusresponse.js  echo.gunk  message.js  status.js  util.go
```
