### ISSUE TITLE
generate: dependency downloading needs tests

### ISSUE THREAD

**Issue by mvdan** [gunk/gunk#175]
This code is tricky to get right and easy to break - we badly need regression tests.

The tests should be skipped in short mode and when there's no network. Testscript has support for all that; see `[net]` in https://godoc.org/github.com/rogpeppe/go-internal/testscript.

The tests should also run even if the developer has protoc installed. Otherwise, we might break the protoc download and not notice for a while.

/cc @vishen

**Comment by vishen** [comment]
Yup, I agree. The downloading of protoc was done pretty hastily, so I don't mind if it gets rewritten along with tests.
