### ISSUE TITLE
download: allow the user to configure the required versions

### ISSUE THREAD

**Issue by mvdan** [gunk/gunk#195]
For example, we can have Gunk v0.1.0 require protoc v3.6.1 by default, but the user might set up their `.gunkconfig` so that it requires a different version like v3.5.0 or v3.6.2 instead.

It should be easy to add a section at the top, like:

```
[versions]
protobuf=v3.6.2
foobar=v1.2.3
```

As part of this, I also think we should check `protoc --version` as part of the download logic, to cover a few scenarios where we do need to download `protoc`:

* the binary exists, but cannot be executed for some reason
* the binary exists, but does something completely different
* the binary exists, but the version is not an exact match

I think we had discussed this at some point, but I can't remember where.

/cc @vishen @kenshaw

**Comment by mvdan** [comment]
> the binary exists, but the version is not an exact match

Note that requiring `v3.6.1` and having `v3.6.1.3` installed would still mean downloading protoc, even if that's unnecessary in most cases. We want Gunk to be as predictable and reproducible as possible.

An alternative approach would be prefix matches; that way, one could require `protobuf=v3.6`, and having `v3.6.1.3` would mean no download is required. However, that means that requiring exact matches could be tricky, as not all third party projects follow semver. For example, `protobuf=v3.6.1` would be a positive prefix match against `v3.6.1.3`, even though both are actual valid protobuf releases.

**Comment by mvdan** [comment]
> we can have Gunk v0.1.0 require protoc v3.6.1 by default

Akin to `go.mod`, we could even go one step further and have the `generate` and `download` commands add the version requirements to the current gunkconfig file, if they're missing. This way, Gunk's behavior would always be exactly the same even if developers have different versions of Gunk installed.

**Comment by vishen** [comment]
This sounds like a good idea to me. 

> Note that requiring v3.6.1 and having v3.6.1.3 installed would still mean downloading protoc, even if that's unnecessary in most cases.

I agree that we should stick to exact matches for this.

> we could even go one step further and have the generate and download commands add the version requirements to the current gunkconfig file, if they're missing

I am not so sure about this. If a `[versions]` section is specified, then we should validate the protoc version for this, but if one isn't specified; I can see situations where people might be using slightly different versions of a tool that are still compatible and would be annoying to upgrade. Although I am happy if we want to enforce this, but I would be against it in general.

**Comment by mvdan** [comment]
> I agree that we should stick to exact matches for this.

Great; I was a bit on the fence about this.

> Although I am happy if we want to enforce this, but I would be against it in general.

Not enforcing versions by default actually sounds fine. After all, we very likely don't want to enforce a single version of Go and Gunk itself, as those would be annoying to most users.

For those who do want to enforce versions, such as some of our projects, they can just add the section. I think it would be helpful for us since sometimes we've had conflicts, due to some devs using v3.5 and others v3.6.

**Comment by mgfcmartinez** [comment]
this was partially addressed in #237. a `[protoc]` section was added for pinning the version/configuring its path (#179), but pinning versions for other useful binaries (e.g. `protoc-gen-go` isn't supported yet.
