### ISSUE TITLE
convert: handle imports

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#198]
When converting a proto file to Gunk, imports are largely ignored, and types from those imports are outputted  as is:

```
# other/file.proto
package other.file;

message Msg {
    string msg = 1;
}
```

```
# example.proto
package example;

import "other/file.proto"

message Request {
    other.file.Msg msg = 1;
}
```

converts to

```
package example

import (
    // other/file.proto
)

type Request struct {
    Msg other.file.Msg `pb:"1"`
}
```

This causes issues for a couple of reasons. 

1) Imports are never actually imported
2) Package names of these imports aren't normalised to be compatible as Go package names.

We could load (and convert) any imports we find for the file being converted, but we won't necessarily know where to find the file unless `gunk convert` is run from the same place as `protoc` is usually run?

We could attempt to force the user to add the file when running `gunk convert`?

**Comment by mvdan** [comment]
I also thought about this briefly, as part of importing Gunk packages with proto files (via convert under the hood). I think we should just omit this for now.

In the long term, if we are to support this, we'd need `convert` to be able to understand Proto directories and how to find them like `protoc` does. Which you could do by relying on `protoc`, as we already rely on it elsewhere.

**Comment by vishen** [comment]
`protoc` looks in a handful of hardcoded paths, and expects the user to pass in the import paths `-I` into the command if the imports are in custom locations, so we could possibly mimic this behaviour when running the `gunk convert` command and allow the user to pass in the import paths.
