### ISSUE TITLE
tests: download protoc every time

### ISSUE THREAD

**Issue by cedric-parisi** [gunk/gunk#214]
It seems that every test scripts are downloading protoc as it's not found in PATH. 

In this [PR](https://github.com/gunk/gunk/pull/213) we are adding the support of `import`, to do so we are using `protoc` to load the imported proto files. Tests were failing because protoc was not found until we call `CheckOrDownloadProtoc` in convert `Run`function.

**Comment by mvdan** [comment]
This is now fixed in master, as they all share a single cache folder thanks to file locks.
