### ISSUE TITLE
gunk generate creating gunkpkg-* in a infinitely loop when import unexisting package

### ISSUE THREAD

**Issue by favadi** [gunk/gunk#244]
Environment:

- OS: macOS 10.14.6
- Go: go1.12.9 darwin/amd64
- gunk: e7b2d674a7945218f7868d02a19154b1f81881ca

Steps to reproduce:

Create a directory outside of GOPATH (ensure that `echo $GOPATH` returns no value).
Create following files:

- accounts.gunk

```gunk
package accounts

import (
	"github.com/gunk/opt/http"
)
```

- .gunkconfig

```ini
[generate]
command=docgen
lang=go
```

Using latest version of gunk, execute `gunk generate accounts.gunk`.

**Expected behavior**: command failed to generate, informed to user about can't find import "github.com/gunk/opt/http".

**Actual behavior**: command stuck forever, creating gunkpkg-* files until terminated.

```
$ ls -1 | head
accounts.gunk
gunkpkg-03871375.go
gunkpkg-077c0591.go
gunkpkg-07d33e8d.go
gunkpkg-0921be6b.go
gunkpkg-09b6d8fe.go
gunkpkg-0aa0459f.go
gunkpkg-0b413492.go
$ cat gunkpkg-03871375.go 
package accounts
```

**Additional Information**: when placing a go.mod file with following content, the gunk generate command works as expected.

```go.mod
module github.com/favadi/playground

go 1.12

require github.com/gunk/opt v0.0.0-20190514110406-385321f21939 // indirect
```

**Comment by mvdan** [comment]
@favadi forgot to notice - remember to add a "Fixes #NNN" line to your commit message, so the issue will be closed automatically.
