### ISSUE TITLE
remove the code to figure out the "latest" version, as it frequently runs into API rate limits

### ISSUE THREAD

**Issue by ghazninattarshah** [gunk/gunk#248]
CI build fails with ```gunk generate ./...
error: could not find platform release asset for ""``` 

Refer: https://travis-ci.org/openbank/openbank/builds/574247172

**Comment by mvdan** [comment]
This is getting worse, probably because we have more tests now than before. I'll have a look.

**Comment by favadi** [comment]
I'll create a PR to add rate limiting to mitigate this.

**Comment by mvdan** [comment]
To quote the interesting bit from the PR:

> The real fix would be to pin gunk to a specific version of protoc by default, letting the user override that in their gunkconfig. It's only the API that has a rate limit, not the actual download link for the archive. We'd lose the ability to figure out what the "latest" version is, but I'd say that's not a big deal. I'd rather have the tool be deterministic and simple.

In other words, partially revert the work that Ken did a few weeks ago to make it figure out what the "latest" version is. I'm sure we can figure out the download URL for an archive, given just:

* the version name
* GOOS
* GOARCH

**Comment by mvdan** [comment]
This is still pretty high priority, as it blocks other gunk work, if anyone wants to tackle it. Just add it as a gunk subtask to this sprint.

**Comment by favadi** [comment]
> This is still pretty high priority, as it blocks other gunk work, if anyone wants to tackle it. Just add it as a gunk subtask to this sprint.

I'll give it a try.
