### ISSUE TITLE
generate: `name` and `json` file descriptor are not in the standard snake_case naming convention

### ISSUE THREAD

**Issue by jwangsadinata** [gunk/gunk#263]
When I was trying to generate the following code from gunk, the resulting proto was not as expected. The example below illustrates the part.

gunk code:
```
type CreateTransferResponse struct {
    TransferID string `pb:"1" json:"transfer_id"`
}
```

generated artifact:
```
type CreateTransferResponse struct {
    TransferID string `protobuf:"bytes,1,opt,name=TransferID,json=transfer_id,proto3" json:"TransferID,omitempty"`
    XXX_NoUnkeyedLiteral struct{} `json:"-"`
    XXX_unrecognized     []byte   `json:"-"`
    XXX_sizecache        int32    `json:"-"`
}
```

I was expecting to see:
```
    TransferID string `protobuf:"bytes,1,opt,name=transfer_id,json=transfer_id,proto3" json:"transfer_id,omitempty"`
```

Which should be as per protobuf naming convention of using snake_case.

**Comment by karel-3d** [comment]
@favadi I think you already fixed this, right

**Comment by jwangsadinata** [comment]
You’re right @karel-3d. This has been addressed by @favadi in https://github.com/gunk/gunk/pull/284. Closing this issue accordingly. Thanks so much guys.
