### ISSUE TITLE
docgen: rethink dependency on pulpMd/markdownfmt

### ISSUE THREAD

**Issue by karelbilek** [gunk/gunk#292]
We are currently depending on [pulpMd](https://github.com/Kunde21/pulpMd) and [our own (maintained just by us basically) fork of markdownfmt](https://github.com/Kunde21/markdownfmt) for docgen

It's annoying for several reasons

- all the bugs need to be fixed in three separate repos - markdownfmt, pulpMd, here
- we need to install the binaries for pulpMd with `go install` when we use `gunk`

There are two ways to solve this

### a) move markdownfmt/pulpMd here, use as library and not binary

Basically, move markdownfmt/pulpMd in here, and use it as library and not binary. We will stop thinking what to install when and the fixes will be on one place.

### b) stop using markdownfmt, simplify pulpMd (and move it here)

Ultimately, I am still not exactly sure why we have the complexity of markdownfmt in the first place.

We basically implement our own markdown formatter, and do magic with the Markdown parsing and AST nodes rendering, just so we can paste code snippets from files into markdown. That seems rather excessive and complex?

What it does allow us is to do magic like

```
> blockquote
>
> {{snippet file [go]}}

1. {{snippet file [go]}}
```

and it will correctly render like

    > blockquote
    >
    > ```go
    > func whatever(){}
    > ```
    
    1. ```go
       func whatever(){}
       ```

which could not be done by just a simple replace, but... we don't really do this anyway, *and* it is not supported by the Hugo version we are using (since its blackfriday markdown parser chokes on this anyway)

and it's not really worth the added complexity of parsing markdown + playing with the AST + rendering it back with custom renderer.

so we could just remove markdownfmt, and simplify pulpMd to just put the file at the snippet place. (and still move it into this repo.)

**Comment by karel-3d** [comment]
cc @favadi and @Kunde21

**Comment by favadi** [comment]
I'm not sure if markdownfmt is absolutely necessary, as in theory we could write the template ourselves to have the exact output we want.

I'm OK with with removing it if it doesn't take too much effort to do.

**Comment by karel-3d** [comment]
from what I get on other channel with @Kunde21 , it was needed for some markdown issues. I would like to know what exact issues are they :)

**Comment by karelbilek** [comment]
I will remove the pulpmd (and markdownfmt) dependency entirely, I could not find (internally) any file where we actually use it.

It's also not in any of the tests.
