### ISSUE TITLE
Gunk generated code currently different from Proto generated code

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#33]
Gunk currently is missing the `opt` option in the `protobuf` tag, this is because we don't return an optional label when converting go types. 

The `protobuf` tag for "name" is different as well, not sure if this is an issue and so far it hasn't caused any issues.

The `json` tag is using whatever the field name is, however this isn't idiomatic json naming; we should convert the name to camel_case if there is no json tag on the gunk struct.

Gunk generated code:
```
type Result struct {
	Success              bool     `protobuf:"varint,1,,name=Success,proto3" json:"Success,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

Proto generated code:
```
type Result struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

**Comment by vishen** [comment]
The options issue was fixed with https://github.com/gunk/gunk/pull/40

**Comment by vishen** [comment]
There is still some differences, but they are expected differences now:

Gunk:
```
type Message struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,json=msg,proto3" json:"Msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

Proto:
```
type Message struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

The `name` is different because we generate from Go code which requires Capitalised variables, but Proto uses lowercase variables. I haven't noticed any problems because of this, except when using `grpc-gateway`, which uses `jsonpb` but sets the [OrigName=true](https://github.com/grpc-ecosystem/grpc-gateway/blob/c203e727a7ca475c659524ed14b695d5ec6acd0c/runtime/marshaler_registry.go#L16) configuration which will use `protobuf:"name=<variable_name>"` when marshalling json. So we need to set a default marshaller:

```Go
func setupGRPCGateway() (*runtime.ServeMux, error) {
        // Create a custom runtime marshaller. This is required because
        // grpc-gateway uses 'JSONPb{OrigName:True}' which will ignore
        // any json specified options and return whatever the protobuf
        // name is.
        // This is due to the fact that the protoc compiler generates
        // json options using an unconfigurable(?) camelCase setting.
        m := &runtime.JSONPb{}
        mo := runtime.WithMarshalerOption("*", m)
        mux := runtime.NewServeMux(mo)
        address := fmt.Sprintf("localhost%s", port)
        opts := []grpc.DialOption{grpc.WithInsecure()}
        ctx := context.Background()
        err := pb.RegisterUtilHandlerFromEndpoint(ctx, mux, address, opts)
        if err != nil {
                return nil, err
        }
        return mux, nil
}
```

**Comment by mvdan** [comment]
We seem to be missing `protobuf:"json=xxx"` too - is that important?

If grpc-gateway hard-codes that, that's pretty annoying. Ideally yes, you're right and we should not do silly things to appease it. Setting up a custom marshaler seems fine for now.

Here's a potentially dumb idea - what about setting `name=msg` instead of `name=Msg`? That is, setting `name` to whatever the JSON name is. I know that's technically wrong, but perhaps other generators will also assume that the original name is all lowercase, or otherwise follows the proto style conventions.

**Comment by vishen** [comment]
> We seem to be missing protobuf:"json=xxx" too - is that important?
Gunk is actually setting that, it is the proto version that doesn't set it. That is the variable that `jsonpb` uses when marshalling and unmarshalling the structs. Gunk is unable to set the `json` tag (which is separate than the `protobuf` tag), or at least I was unable to find away to set it.

> Here's a potentially dumb idea - what about setting name=msg instead of name=Msg? 
I did consider that, and we can do that if we want, but it seemed a bit weird to do it just to appease `grpc-gateway` - however, in saying that, if all the other libraries use that as a json name, then it would make sense to change it.

**Comment by mvdan** [comment]
Gotcha. I think we should leave things as they are now, use that marshaler workaround temporarily, and see how that works - in particular as we include other generators. If it turns out that grpc-gateway is an outlier, we can ignore its requirements. If it turns out that its assumptions are widespread, we can consider adopting them.

**Comment by vishen** [comment]
I agree. I will close this as the issues are currently fixed or expected.
