### ISSUE TITLE
Parsing '+gunk' syntax gives slightly unhelpful error message when it fails.

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#35]
When the parsing of `+gunk` syntax fails, it would be helpful if it gave a better error message (if possible). For the below invalid gunk, it gives `error: eval:2:3: expected 'EOF', found Method` - it is useful if I knew it was parsing the below, but I had no idea. 

If we could point to the actual line number in the file or the function it is parsing, that might be enough to help people track down the issue.

```
        // +gunk http.Match
        //              Method: "POST",
        //              Path:   "/v1/echo",
        //              Body:   "*",
        //      }
        Echo(Message) Message
```

**Comment by mvdan** [comment]
Yes, this is because we use `types.Eval`, which at the moment has zero idea of where the syntax is within the file. I think I can improve this somehow.
