### ISSUE TITLE
Use gunk fmt on the converted proto to gunk code

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#60]
Since we now have gunk fmt, gunk fmt should be run on any converted proto to gunk code. Not sure how difficult this would be, but having nicely formatted gunk converted code would be good.

**Comment by mvdan** [comment]
Should be fairly straightforward, as formatting can happen on a per-file basis. To make your life easier, I could even add a piece of API to format a file in-memory, so that you don't have to write to disk twice.

**Comment by vishen** [comment]
I think that would be quite handy if possible :)

**Comment by mvdan** [comment]
Yup, should be easy. We could mirror the API in https://golang.org/pkg/go/format/#Source.
