### ISSUE TITLE
Only include imports that are used when building the proto filedescriptor

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#66]
We get the following warnings sometimes when using protoc to generate language bindings:

```
echo.proto: warning: Import github.com/gunk/opt/opt.gunk but not used.
echo.proto: warning: Import github.com/gunk/opt/http/http.gunk but not used.
```

This is because we include all imports in the proto filedescriptor, even if they aren't being used. We should remove these imports if they aren't used, although I am unsure how hard this will be.

**Comment by mvdan** [comment]
The opt and http protos are actually empty - they're just special ones we treat while transforming from gunk to proto. So they can always be ommitted from the generate requests.
