### ISSUE TITLE
Recursive imports for gunk packages.

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#68]
When using `protoc` as a code generator, we are currently getting cyclic imports if we have more than one gunk file in a gunk package:

```
gunk/testdata/generate/echo.gunk: File recursively imports itself: gunk/testdata/generate/echo.gunk -> gunk/testdata/generate/types.gunk -> gunk/testdata/generate/echo.gunk
```

And looking at the proto files and their dependencies you can see the cyclic imports occurring (this is taken from the test)

```
FILENAME: github.com/gunk/opt/http/http.gunk
FILENAME: google/protobuf/duration.proto
FILENAME: google/protobuf/empty.proto
FILENAME: google/protobuf/timestamp.proto
FILENAME: testdata.tld/util/echo.gunk
  DEPENDENCY: google/protobuf/empty.proto
  DEPENDENCY: google/protobuf/timestamp.proto
  DEPENDENCY: google/protobuf/duration.proto
  DEPENDENCY: testdata.tld/util/types.gunk
  DEPENDENCY: github.com/gunk/opt/http/http.gunk
  DEPENDENCY: testdata.tld/util/imported/imp.gunk
FILENAME: testdata.tld/util/imported-notarg/imported.gunk
FILENAME: testdata.tld/util/imported/imp.gunk
FILENAME: testdata.tld/util/types.gunk
  DEPENDENCY: testdata.tld/util/echo.gunk
```

@mvdan was suggesting we combine all gunk files in a package into one proto file

**Comment by mvdan** [comment]
The only thing this should affect is that we end up generating one output file per Gunk package, and not per Gunk file. This seems fine to me. After all, compiling a Go package results in a single object file, and not one object file per Go file. Similarly, one cannot type-check a single Go file, as type-checking happens on a per-package basis.

Jon was saying that the generators that support cyclic dependencies (such as `protoc-gen-go`) could keep on generating one output file per Gunk file, but I think it's best if we keep the behavior across generators consistent. Ideally, all generators and plugins should be treated equally. I also don't want to trust `protoc-gen-go` to keep on being happy with circular dependencies.
