### ISSUE TITLE
look into a simpler replacement for grpc-gateway

### ISSUE THREAD

**Issue by mvdan** [gunk/gunk#77]
@kenshaw had some ideas for this. For example, grpc-gateway fires up an extra HTTP server to proxy requests to the grpc server, which is unnecessarily complex (e.g. requires extra care with TLS since we need to dial) and also a bit wasteful.

I'm not clear on what a replacement would look like; this is an issue so we can discuss the design. /cc @vishen

**Comment by vishen** [comment]
One thing it should do (which is currently annoying with `grpc-gateway`); for url params, it should use the proto json name, rather than the proto name:

```
type ProjectRequest {
    ID string `pb:"1" json:"id"`
}

type ProjectService interface {
	//
	//
	// +gunk http.Match{
	//         Method: "GET",
	//         Path:   "/v1/projects/{ID}",
	// }
	Get(ProjectRequest) Project
}
```

it would be good if we could us `/v1/projects/{id}` (the proto json name), but maybe that won't always make sense? Will have to see.
