### ISSUE TITLE
Unable to return a list in a Gunk interface function 

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#81]
There seems to be a problem when trying to return a list from a gunk interface function. When generating the Go code for an interface function returning a list, it seems to return a single instance rather than a list. Haven't looked at it yet, so not sure what might be going on.

The following:
```
type DotService interface {
	//
	//
	// +gunk http.Match{
	//         Method: "GET",
	//         Path:   "/v1/dots",
	// }
	List() []Dot
}
```
produces:
```
type DotServiceServer interface {
	List(context.Context, *empty.Empty) (*Dot, error)
}
```

**Comment by mvdan** [comment]
Can you even return a `repeated T` from a grpc endpoint? I assumed we could only take or return one message (struct).

**Comment by vishen** [comment]
Ah, I didn't think about that. Very likely not? Maybe we should error if someone attempts to do that?

**Comment by mvdan** [comment]
Yup, something to fix either way.
