### ISSUE TITLE
config: shortened generate stanza is only for protoc

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#96]
Our shortened generate stanza in a gunkconfg file is currently always a short-hard for the `protoc` command:

```
[generate js]

[generate go]
plugins=grpc
```

is short-hand for

```
[generate]
protoc=js

[generate]
protoc=go
plugins=grpc
```

which will invoke protoc like the following; `protoc --js_out` and `protoc --go_out=pluings=grpc`. We will likely want the shortened generate to work for both the protoc command and protoc-gen-* commands.

One way would be to check what `x` is in `[generate x]` and if it is a language that protoc can generate code for (https://github.com/protocolbuffers/protobuf#protobuf-runtime-installation), we expand that to be:

```
[generate]
protoc=<x>
```

but if it isn't a language that protoc can generate code for, we assume that is it a protoc-gen-* plugin, and expand it to

```
[generate]
command=protoc-gen-<x>
```

**Comment by kenshaw** [comment]
No one is going to create a `js` generator project called `protoc-js`. Same for `python`, `java`, `ruby` and the other built in generators. I would just suggest making it only for those. If someone does want to use that in the `.gunkconfig`, then they can override using the `command=` key.

**Comment by kenshaw** [comment]
Ignore my last comment. Too early in the morning, and not enough coffee.

**Comment by kenshaw** [comment]
The logic for this should probably be:

```go
lang := "js"
cmdpath, err := lookpath(lang, "protoc-gen-"+lang)
if err != nil { /* ... */ }

func lookpath(names ...string) (string, error) {
    for _, n := range names {
        if z, err := os.LookPath(n); err == nil { 
             return z, nil
        }
    }
   return errors.New("could not find path")
}
```
(or similar)
