### ISSUE TITLE
Should we have a base or a default config?

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#99]
Currently, we have a hardcoded default config that will be used if there is no other configs found, if a gunkconfig is found in a the project root, or any sub-folders, that .gunkconfig will be used and the default config is ignored. The alternative is, to have this as a base config, and gunkconfig's found in sub-folders are appended to the base config.

If we went with the hardcoded base config, we will likely need some way for the user to override the base config. This could be achieved by having a .gunkconfig in the root of the project, if that exists, that will be used as the base config, otherwise, we will use the default base config.

**Comment by vishen** [comment]
As per discussions in the call. We will drop the idea of a base or default config, and instead show an error when no `.gunkconfig` is found.

**Comment by mvdan** [comment]
I think that new logic will be much simpler :)

**Comment by vishen** [comment]
I created https://github.com/gunk/gunk/issues/101 to track this.
